baseurl = "http://http://beijing-elandsystems.github.io"
languageCode = "en-us"
title = "Beijing Elandsystems Tech News"
disqusShortname = "tanksuzuki"

[Params]
# subtitle = "I would like to be a layer 3 switch."
# facebook = "https://facebook.com/foobar"
# twitter = "https://twitter.com/foobar"
# github = "https://github.com/foobar"
# showsRSS = true
profile = "/images/profile.png"
copyright = "Beijing ELANDSYSTEMS Technology Development CO., LTD"
# analytics = "UA-XXXXXXXX-X"
# shareThis = "XXXXXXXX-XXXX-XXXX-XXXX-XXXXXXXXXXXX"
